[feat] DatePicker 컴포넌트 구현
tickita-project/tickita-front pull request #13
Opened 2024-05-31 04:16 UTC by jae6269

# 🎯 이슈 번호

- #11  

## 🏁 작업 내용

- DatePicker 컴포넌트의 기능을 구현
- 추후 디자인이 추가될수 있도록 클래스네임 설정

## 🖼️ 스크린샷 or 동작 영상(선택)
![image](https://github.com/tickita-project/tickita-front/assets/79738890/2bc0491b-62ab-48ec-9e36-3514c80cd4df)

## 💬 리뷰 요구 사항(선택)

ex) - OO 로직은 백엔드 API가 아직 완성되지 않아서 Mock 데이터 사용하고 추후에 수정 할 예정입니다.

- 대시보드페이지에서는 hasArrowButton 프롭에 false를 넘겨주고, 겉을 Link 컴포넌트로 감싸서 사용가능합니다
- 현재는 PR용으로 선택된날짜(파란색) 이전/다음달(회색)으로만 스타일링 되어있고, 디자인이나오면 따로 PR올릴 예정입니다

2024-05-31 05:34 UTC, wo-o29 commented
고생하셨습니다 제가 Date객체를 다룬 적이 없어서 굉장히 어렵네요... 계속 보면서 공부하도록 하겠습니다!
`onClick` 같은 이벤트는 `handle~~`로 사용해도 될 것 같아요~!

2024-05-31 09:07 UTC, jae6269 commented
> 고생하셨습니다 제가 Date객체를 다룬 적이 없어서 굉장히 어렵네요... 계속 보면서 공부하도록 하겠습니다! `onClick` 같은 이벤트는 `handle~~`로 사용해도 될 것 같아요~!

반영했습니다!

2024-05-31 17:30 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +  const isSameDay = (toDay: Date, compareDay?: Date | null) => {
이함수 사용안해서 삭제되었습니다..! 첨에 실험용으로 막 하다가 잘못넣었나봐요..

2024-05-31 17:31 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +  today.setHours(0, 0, 0, 0);
아래부분에서 날짜 비교할때 오류가날줄 알았는데 실험해보니 똑같군요! 감사합니다

2024-05-31 17:31 UTC, jae6269 commented on components/DatePicker/datePicker.module.scss
아하 일단 파스칼 맞춰놓았습니다

2024-05-31 17:34 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +  };
아 맞네요 제시하신게 더 좋아보여요 근데 이함수 삭제되어서 변경사항은없겠습니다

2024-05-31 17:34 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +  const daysOfWeek = ["일", "월", "화", "수", "목", "금", "토"];
이부분은 생각중이었어서 빼놓고 메인캘린더 작업할때에도 쓰려고합니다

2024-05-31 17:35 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +  const [currentMonth, setCurrentMonth] = useState<Date>(new Date());
첨에 실험용으로 해서 이 state도 삭제되었습니다 ㅎ 상위 페이지부분에서 내려줄거에요

2024-05-31 17:36 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
> +      else acc[acc.length - 1].push(day);
일단 추가해놓았습니다  저는 사용하는게 깔끔해보이네요!

2024-06-01 02:09 UTC, wo-o29 commented on components/DatePicker/datePicker.module.scss
넵 이것도 오늘 한번 얘기해보죠!

2024-06-01 02:10 UTC, wo-o29 approved these changes

2024-06-01 02:25 UTC, wo-o29 commented on components/DatePicker/DatePicker.tsx
> +import VerticalDivider from "@/public/Icons/vertical-divider-logo.svg";
저희 이미지는 src에 문자열로 넣는 방식이였던 것 같아요! `(@/public 없이 바로 / 사용해도 무방할 것 같네요)`

```jsx
<Image src="/icons/arrow-left-icon.svg">
```

2024-06-01 02:25 UTC, wo-o29 commented on components/DatePicker/DatePicker.tsx
> +          <Image src={VerticalDivider} alt="divider" />
```suggestion
          <Image src={VerticalDivider} alt="divider" />
```
오 import 방식은 `width`, `height`를 생략해도 되는군요 layout shift도 안생기나요??

2024-06-01 02:25 UTC, wo-o29 commented on styles/_fonts.scss
> +@mixin caption2-medium($color: black) {
오... scss 고수이시군요.. 
`font-family`, `font-style`은 지우고 `font-size`는 `rem` 단위로 바꾸면 좋을 것 같아요!

2024-06-02 04:33 UTC, NJ97S commented on public/Icons/arrow-left-icon.svg
P1: 현재 `Icons` 폴더명 `icons`로 수정 부탁드립니다. (저는 어제 `Icons` 폴더 삭제 후 push -> `icons` 폴더 생성 후 push로 폴더명 변경했어요!!)

2024-06-02 04:46 UTC, NJ97S commented on components/DatePicker/datePicker.module.scss
P1: `px` -> `rem`으로 수정부탁드려요 🥹

2024-06-02 04:48 UTC, NJ97S commented on styles/_fonts.scss
> +}
`mixin`이라니... 진짜 고수시군요 🐸🐸🐸

2024-06-02 04:51 UTC, NJ97S commented on components/DatePicker/DatePicker.tsx
> +              <Image src="/icons/arrow-right-icon.svg" alt="다음달" width={20} height={20} />
P1: 코드 내 이미지 파일 경로에 `Icons`로 들어간 곳도 있고 `icons`로 들어간 곳도 있는데, 수정 부탁드려용

2024-06-02 04:51 UTC, NJ97S requested changes
수고하셨습니당 👍👍👍

2024-06-02 04:52 UTC, NJ97S commented on components/DatePicker/DatePicker.tsx
> +          <Image src="/Icons/vertical-divider-logo.svg" alt="divider" width={1} height={10} />
P3: `alt="divider"` 부분도 html lang에 맞춰서 한국어로 수정해주시면 좋을 것 같아요

2024-06-02 07:28 UTC, wo-o29 approved these changes

2024-06-02 12:41 UTC, NJ97S approved these changes
수고하셨습니당🔥👍👏👏👏👏👏👏

2024-06-02 12:41 UTC, merged