feat: 캘린더페이지 사이드바 및 기본 레이아웃 설정
tickita-project/tickita-front pull request #30
Opened 2024-06-05 07:27 UTC by jae6269

# 🎯 이슈 번호

- #28 
- #29 

## 🏁 작업 내용(필수)

- 캘린더 페이지 레이아웃 (초기설정)
- 캘린더 사이드바 컴포넌트 레이아웃
- useOutsideClick 훅 구현 

## 💬 리뷰 요구 사항

- 추후에 캘린더는 디자인이 나오면 디자인 , 기능 을 따로 분리해서 PR올릴 계획입니다
- 아직 컬러체크박스로 그룹 리스트부분은 추가 안되어있어요!

## 📢 참고 사항

-
-

2024-06-05 09:28 UTC, wo-o29 approved these changes
수고하셨습니다🫡👏👍🫡👏👍🫡👏👍🫡👏👍🫡👏👍
캘린더 페이지에도 `<MetaData title="캘린더 페이지 이름" />` 넣어줘도 좋을 것 같아요!

2024-06-05 09:53 UTC, jae6269 commented on pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
> +        <td key={i} className={cn()}>
아 월 / 주 / 일 메인캘린더는 아직 컴포넌트 만들고 연결만 해둔 상태입니다!

2024-06-05 10:04 UTC, jae6269 commented on pages/calendar/components/CalendarSideBar/index.tsx
> +      <DatePicker selectedDay={selectedDay} setSelectedDay={setSelectedDay} hasNavigation={true} />
이거 이렇게되는지 첨알았네요..? 배워갑니다..

2024-06-05 10:05 UTC, jae6269 commented on pages/calendar/index.page.tsx
> +          <CalendarTypeRadioButton setType={setCalendarType} />
원래 저도 맞추는데 놓쳤네요 감사합니다!

2024-06-05 10:12 UTC, jae6269 commented on components/DatePicker/DatePicker.tsx
>        const isThisMonthDay = !day.isSame(viewDate, "month");
아뇨 안해줘도 똑같긴해요!

2024-06-05 10:18 UTC, jae6269 commented on pages/calendar/index.page.tsx
> +        />
옵셔널로하고 기본값을 true로 설정하도록 처리했습니다

2024-06-05 15:48 UTC, jae6269 commented on pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
넵 스타일 확정되면 변수로 변경해놓을게요!

2024-06-06 05:12 UTC, NJ97S commented on components/ColorCheckBox/ColorCheckBox.module.scss
> +  height: 44px;
P1: `rem`으로 수정 부탁드려요

2024-06-06 05:17 UTC, NJ97S commented on components/DatePicker/datePicker.module.scss
> +  gap: .375rem;
P4: 통일성을 위해 `.375` -> `0.375`로 변경하는 것도 좋을 것 같아요

2024-06-06 05:19 UTC, wo-o29 approved these changes

2024-06-06 05:19 UTC, wo-o29 commented on pages/calendar/components/CalendarGroupList/index.tsx
> +          </React.Fragment>
```suggestion
          <ColorCheckBox key={group.id} color={group.groupColor} title={group.groupName} />
```
p4: 여기 `Fragment ` 없이 `ColorCheckBox`에 직접 `key`를 부여하면 문제가 생길까요??

2024-06-06 05:19 UTC, NJ97S commented on pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
> +      gap: .25rem;
P4: 여기도 통일성을 위해 `0.75rem`, `0.25rem`과 같이 작성하는 것도 좋을 것 같아요

2024-06-06 05:20 UTC, NJ97S commented on pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
> +        padding: 10px;
P1: `rem`으로 수정 부탁드려용

2024-06-06 05:23 UTC, NJ97S commented on styles/_fonts.scss
>    font-style: normal;
P3: `font-style: normal`은 기본 설정값이라 작성하지 않아도 괜찮을 것 같아요

2024-06-06 05:24 UTC, NJ97S requested changes
수고하셨습니당 👍🔥🩷👍🔥🩷👍🔥🩷👍🔥🩷👍🔥🩷👍🔥🩷

2024-06-06 06:53 UTC, jae6269 commented on pages/calendar/components/CalendarGroupList/index.tsx
> +          </React.Fragment>
찾아보니까 지금같을때는 단일 컴포넌트 map이라서 바로쓰는게 더 좋다고 하네요!

2024-06-06 06:56 UTC, jae6269 commented on styles/_fonts.scss
>    font-style: normal;
여기파일에서 제가한건 mixin 부분이라서 이부분은 일단은 그대로 두겠습니다!

2024-06-06 07:55 UTC, NJ97S approved these changes

2024-06-06 08:47 UTC, merged