[feat] 그룹 생성 모달
tickita-project/tickita-front pull request #35
Opened 2024-06-06 17:26 UTC by wo-o29

# 🎯 이슈 번호

- #25 

## 🏁 작업 내용(필수)

- 그룹 생성 모달 추가

## 💬 리뷰 요구 사항

- `react hook form`, `zod` 마스터 남주님이 보시기에 부족한 부분 있다면 피드백 부탁드릴게요!

## 📢 참고 사항

- api는 아직 나오지 않아서 추후에 추가 할 예정입니다.

2024-06-07 05:11 UTC, NJ97S commented on components/Header/Header.module.scss
> +          padding: 0rem 0.5rem 0 0;
P3: 이렇게 적어도 괜찮을 것 같아요

```scss
padding:0 0.5rem 0
```

2024-06-07 05:12 UTC, NJ97S commented on components/Header/Header.module.scss
> +          padding: 0rem 0.5rem 0 0;
P4: 통일성을 위해 `0rem`도 `0`으로 적어주셔도 좋을 것 같아요

```scss
padding: 0 0.5rem 0 0;
```

2024-06-07 05:16 UTC, NJ97S commented on components/Header/index.tsx
> +            loading="eager"
P4: 즉시 로딩도 되면서 사전 로드까지 시킬 수 있는 `priority`를 사용해보는 것도 좋을 것 같아요

2024-06-07 05:37 UTC, NJ97S commented on components/Input/index.tsx
> +        {isRequired ? <span className={cn("required-field")}>*</span> : <span>(선택)</span>}
P1: 삼항연산자를 사용할 경우에는 `false` 값 외의 falsy 값들도 다 처리가 되기 때문에, 이렇게 할 경우 `이메일` 옆에도 `(선택)` 글자가 생겨서, 구분하여 코드를 작성했었습니다. 제가 댓글을 따로 달았어야 했는데 그냥 넘어갔던 것 같아요... 죄송합니당...😭 그리고 `(선택)` 부분 className이 삭제된 것 같아요...!

2024-06-07 05:38 UTC, NJ97S commented on components/Input/index.tsx
> +      <input ref={ref} id={id} {...restProps} className={cn({ "error-style": errorMessage })} />
테두리는 미처 생각하지 못했는데 역시 갓우혁 👍👍👍

2024-06-07 05:39 UTC, NJ97S commented on components/Modal/CreateGroup/index.tsx
> +import { useState } from "react";
P1: 해당 import 문은 제거해도 괜찮을 것 같아요

2024-06-07 05:41 UTC, NJ97S commented on components/Modal/CreateGroup/index.tsx
> +  console.log(selectColor);
P1: 콘솔 코드 제거 부탁드립니당 🫡

2024-06-07 05:43 UTC, NJ97S commented on components/Modal/CreateGroup/CreateGroup.module.scss
> +          }
hover 애니메이션까지 신경써주신거 진짜 너무 좋네요 👍👍👍

2024-06-07 05:43 UTC, NJ97S commented on components/Modal/CreateGroup/CreateGroup.module.scss
> +        }
컬러 선택할때도 부드럽게 체크가 생겨서 너무 예쁜 것 같습니다 👍👍👍

2024-06-07 05:47 UTC, NJ97S requested changes
수고하셨습니당 🥰😆🔥🥰😆🔥🥰😆🔥🥰😆🔥

2024-06-07 06:20 UTC, wo-o29 commented on components/Header/index.tsx
> +            loading="eager"
`loading="eager"`는 페이지 로딩 시 이미지는 즉시 로드하고 `priority `는 로딩의 우선 순위를 설정하는거라 `loading="eager"` 이게 더 빠르지 않나요??

2024-06-07 06:23 UTC, wo-o29 commented on components/Input/index.tsx
> +        {isRequired ? <span className={cn("required-field")}>*</span> : <span>(선택)</span>}
`isRequired`  자체가 boolean 타입을 받지 않나요...? false 값 외의 falsy한 값이 들어올 수 가 있나요?? 
선택 부분은 다 기본 css 값을 가지고 있어서 제거 하였습니다!
```
   .selective-field {
      color: $black;
      font-weight: 400;
    }
```

2024-06-07 06:59 UTC, NJ97S commented on components/Input/index.tsx
> +        {isRequired ? <span className={cn("required-field")}>*</span> : <span>(선택)</span>}
불리언값을 받기는 하지만, 이메일과 같이 값이 넘어가지 않는 경우에도 falsy로 처리가 되는 것 같더라구요...! 실제로 화면에 출력해보시면 이메일 옆에도 (선택) 이라고 나옵니다ㅠ

2024-06-07 07:01 UTC, NJ97S commented on components/Input/index.tsx
> +        {isRequired ? <span className={cn("required-field")}>*</span> : <span>(선택)</span>}
그리고 상위 태그 스타일 속성 때문에 해당 코드를 지우면 스타일이 반영되지 않습니다... 화면으로 출력해보시면 굵은 글씨로 나와요ㅠㅠ css 코드 복구 부탁드립니다ㅠㅠ

2024-06-07 07:25 UTC, NJ97S commented on components/Header/index.tsx
> +            loading="eager"
![image](https://github.com/tickita-project/tickita-front/assets/79499733/79dd9baa-32e7-43fd-a572-fe7566e3bae0)

![image](https://github.com/tickita-project/tickita-front/assets/79499733/b2f9bdb8-43d0-4a9b-b8e6-d28fd6cb6eda)

공식문서 상으로는 `priority`를 사용하면 preload를 할 수 있는거고, `loading="eager"`의 경우는 preload 까지는 아니고 그냥 이미지를 즉시 로드해준다는 이야기 인 것 같아서 말씀드려봤습니다.

그리고 next에서는 `loading` 속성을 건드리는 것보다는 `priority`를 사용하는 것을 권장하는 것 같아요 😶

2024-06-07 09:50 UTC, tead7 approved these changes
열심히 할 말을 찾고 있는데 따로 할 말이 없군요!
수고하셨습니다.

2024-06-07 15:05 UTC, jae6269 requested changes
css 폰트 재사용만 해주시면 좋을거같아요 ! 로직에서는 다 잘해주신거같아요! 수고하셨습니다 :)

2024-06-08 02:43 UTC, wo-o29 commented on components/Header/Header.module.scss
> +        .notification-bell {
종이랑 짱구 사이에 닉네임 텍스트가 있는데 종만 왼쪽으로 옮겨 달라는 말씀이신가요?? 아니면 종 + 닉네임을 프로필 사진이랑 여백을 추가 해달라는 말씀이신가요??

2024-06-08 02:43 UTC, wo-o29 commented on components/Modal/CreateGroup/CreateGroup.module.scss
> +        transform: rotate(180deg);
저도 완전 기본적인 것만 응용하는거라서 `opacity`, `transform` 말고는 잘 모르겠네요....ㅋㅋㅋㅋ

2024-06-08 02:43 UTC, wo-o29 commented on components/Header/Header.module.scss
> +            font-size: 0.75rem;
근데 폰트같은거 mixin으로 사용하려면 디자이너가 한 곳에 정리해둔 것보고 mixin으로 정의해야 하지 않나요??
저희가 하나하나 보면서 여러 곳에서 쓰이는지 파악하고 mixin으로 정의가 되어있는지 확인하는건 너무 리소스가 큰 것 같아서...

2024-06-08 05:13 UTC, NJ97S approved these changes

2024-06-08 11:11 UTC, jae6269 commented on components/Header/Header.module.scss
> +        .notification-bell {
종만 조금 왼쪽으로 해달라는 말이었습니다!

2024-06-08 11:13 UTC, jae6269 commented on components/Header/Header.module.scss
> +            font-size: 0.75rem;
저는 그냥 피그마에서 include 하고 폰트 이름 쳐서 정의 해둔거면 에디터가 자동으로 띄워줘서 사용하고있긴해요

2024-06-08 11:26 UTC, jae6269 approved these changes

2024-06-13 10:19 UTC, jae6269 approved these changes
역시 잘하시네요 !! 보면서 공부 되었습니다 수고하셨습니다 :)

2024-06-13 10:19 UTC, jae6269 commented on components/Modal/CreateGroup/index.tsx
> +          >
p3: 여기서 버튼 disabled 시키지않고 classname에 추가하시는 이유가 있을까요?

```suggestion
            disabled : {!isValid || isPending }
```

2024-06-13 10:53 UTC, NJ97S commented on components/Input/index.tsx
> +        {isRequired == false && <span className={cn("selective-field")}>(선택)</span>}
P3: 이 부분 `===`를 써주는 것도 좋을 것 같아요

2024-06-13 10:54 UTC, NJ97S commented on components/Modal/CreateGroup/index.tsx
> +import { useQueryClient } from "@tanstack/react-query";
P1: 사용되지 않는 import문이라 제거해주시면 좋을 것 같아요

2024-06-13 11:00 UTC, NJ97S commented on components/Notification/BaseNotification/index.tsx
P2: `schduleInfo` -> `scheduleInfo` 오타 수정 부탁드려욥

2024-06-13 11:01 UTC, NJ97S commented on constants/calendarConstants.ts
> +export const DAYS = ["일", "월", "화", "수", "목", "금", "토"] as const;
👍👍👍

2024-06-13 11:01 UTC, NJ97S commented on constants/queryKey.ts
> + */
친절하게 참고 링크까지 👍👍👍 감사합니다 🥹🥹🥹

2024-06-13 11:03 UTC, NJ97S commented on pages/api/cookies.page.ts
>    }
이 부분은 없으면 오류가 생겨서 넣어주셨을까요? 😶😶😶

2024-06-13 11:07 UTC, NJ97S commented on pages/dashboard/index.page.tsx
> +  setContext(context);
context에서 cookie를 가져오기 위해, axios 쪽으로 context를 넘겨주는 코드입니다.

해당 `getServerSideProps`에서 cookie를 가져오는 코드까지 작성하여도 되지만, 그렇게 할 경우, 반복된 코드가 불필요하게 발생하게 될 것 같아, 관련 로직은 axios 파일에 공통으로 넣어두었습니다!

2024-06-13 11:29 UTC, wo-o29 commented on pages/dashboard/index.page.tsx
> +  setContext(context);
> p5: 혹시 이거 해주는 의미가 어떤건가요??? 함수 봤는데 이해가 안돼서..

저희가 `Authorization` 토큰을 넣어주는 방식이 `interceptors.request`로 가로채서 넣어주고 있는데 클라이언트에서 api 요청을 할 때는 정상적으로 헤더에 저희가 넣어둔 쿠키가 나오는데 SSR 환경에서 api 요청을 하면 헤더에 있는 쿠키가 찍히지 않아서 찾은 방법이 SSR에서 접근 가능한 `context` 객체를 넘겨줘서 쿠키에 접근하는 방식으로 사용중입니다.
일단 지금까지 찾은 방법은 `context` 객체를 넘겨주는 방식인데 다른 방식도 알아보려고 하고 있습니다!

2024-06-13 11:30 UTC, wo-o29 commented on components/Modal/CreateGroup/index.tsx
> +          >
잊고 있었네요... disable주고 그걸 스타일링 했어야 했는데.. 감사합니다!!

2024-06-13 11:41 UTC, wo-o29 commented on pages/api/cookies.page.ts
>    }
로컬에서는 저희 서버랑 next.js 서버가 둘 다 `localhost:3000`이라서 없어도 문제 없었는데 PR 프리뷰에서 요청가니깐 에러 생기더라구요 아마 저희 배포 사이트도 같을 것 같아서 추가했습니다(그래도 아직 백엔드 서버가 http라서 프리뷰 사용은 안되네요... https로 바뀌고 그때도 한번 테스트 해봐야 할 것 같아요!)

2024-06-13 11:43 UTC, NJ97S reviewed
역시 고수시군요 👍👍👍 수고하셨습니다 🥰🔥😆🥰🔥😆🥰🔥😆🥰🔥😆

2024-06-13 12:40 UTC, merged

2024-06-13 12:41 UTC, jae6269 commented on pages/dashboard/index.page.tsx
> +  setContext(context);
일타강사 두명이시네요 감사합니다