[feat] 로그인 시 쿠키에 토큰 저장
tickita-project/tickita-front pull request #40
Opened 2024-06-09 13:28 UTC by NJ97S

# 🎯 이슈 번호

- #39 

## 🏁 작업 내용(필수)

- 로그인 시 cookie에 `accessToken`과 `refreshToken`이 저장됩니다.
- axios interceptor를 추가하였습니다.

## 📢 참고 사항

- 급하게 만든거라, 아직 회원가입 후에는 쿠키에 토큰 저장이 되지 않습니다...😭
- `postRequest` 함수 사용해보시고, 혹시나 문제가 생긴다면 알려주십셔...

2024-06-09 14:01 UTC, wo-o29 requested changes
수고하셨습니다! ⭐️👍🙃⭐️👍🙃⭐️👍🙃⭐️👍🙃⭐️👍🙃
저도 쿠키 설정 안해봐서 부족한데 열심히 공부해보도록 하겠습니다 !_!

2024-06-10 01:13 UTC, tead7 approved these changes
수고하셨어요~

2024-06-10 01:13 UTC, tead7 commented on apis/axios.ts
>    baseURL: process.env.NEXT_PUBLIC_BASE_API_URL,
const BASE_API_URL = process.env.NEXT_PUBLIC_BASE_API_URL;
상수로 빼도 괜찮을 거 같아요

2024-06-10 02:19 UTC, NJ97S commented on pages/sign-in/kakao/index.page.tsx
> +  }
헉... 나름 테스트해본다고 하긴 했는데... 이전에 테스트했던 accessToken이 남아있는 상태로 테스트해서, 잘 되는 것처럼 보였나봐요... 죄송함다... 수정하겠습니다😢

자바스크립트로 `document.cookie`를 사용하게 될 경우에는 쿠키 정보 탈취 가능성이 있다고 알고 있어, 의도적으로 접근을 막아두었습니다. 혹시 자바스크립트를 통한 접근 방식이 필요하실까요?

2024-06-10 02:20 UTC, NJ97S commented on apis/axios.ts
> +});
토큰이 발급되기 전까지의 과정에는 `interceptor`가 필요하지 않아서, 분리를 해두었습니다!

2024-06-10 02:21 UTC, NJ97S commented on apis/axios.ts
> +});
`GET` 요청 시에도 토큰이 동일하게 들어가야 한다면, 이름을 수정해보겠습니다 🫡

2024-06-10 02:24 UTC, wo-o29 commented on pages/sign-in/kakao/index.page.tsx
> +  }
남주님이 만들어주신 `getCookie` 함수에서도 `document.cookie`로 쿠키에 접근하지 않나요...?

2024-06-10 02:27 UTC, wo-o29 commented on apis/axios.ts
> +});
`instance`에 `interceptor`를 설정하고 `accessToken`이 있으면 헤더에 넣어주면 되지 않을까요??
```js
instance.interceptors.request.use((config) => {
  const isServer = isSever();

  const accessToken =  isServer ? "서버에서 토큰 가져오는 로직" : "클라이언트에서 토큰 가져오는 로직";

  if (accessToken) {
    config.headers.Authorization = `Bearer ${accessToken}`;
  }

  return config;
});
```
제 개인적인 생각은 `instance`에 `interceptor`를 설정하는게 `postRequest`를 따로 만드는 것보다 일관성 있을 것 같네요!

2024-06-10 03:09 UTC, NJ97S commented on utils/getCookie.ts
> +  );
어제는 만들어둔 axios를 사용해보지는 않았는데...😭 유사한 코드로 이전 프로젝트에서 Next app router로 테스트 했을 때는 잘 되긴 했습니다!! 혹시 접근 안되서 오류가 생기나요...?

2024-06-10 03:11 UTC, NJ97S commented on apis/axios.ts
>    baseURL: process.env.NEXT_PUBLIC_BASE_API_URL,
axios 함수가 여러 개가 될 경우에는 상수로 빼는 게 더 좋긴 하겠네요!! 코드 수정 후에, 반복 사용이 될 경우에는 상수화 시켜보도록 하겠습니다 👍👍👍

2024-06-10 03:27 UTC, wo-o29 commented on utils/getCookie.ts
> +  );
`app router`랑 `HttpOnly`랑 연관이 있나요??

2024-06-11 05:12 UTC, jae6269 approved these changes
어려운작업인거같네요 ㅠ 수고하셨습니다 ! :) 로그인처리를 저도 잘 몰라서 찾아보면서 리뷰했어요!!

2024-06-11 05:12 UTC, jae6269 commented on apis/axios.ts
>  instance.interceptors.response.use();
에러처리는 추후에 구현하는건가요??

2024-06-11 05:12 UTC, jae6269 commented on apis/axios.ts
> +  config.headers.Authorization = `Bearer ${token}`;
```
if (isTokenExpired(token)) {
    token = await refreshToken();
    // 쿠키에 토큰 새걸로 리셋
  }
```
p2: 이런식으로 만료되었을때 처리 해줘야할거같아요
ex : https://velog.io/@jhc729/React-Axios-%EC%9D%B8%ED%84%B0%EC%85%89%ED%84%B0-%EC%82%AC%EC%9A%A9%EB%B2%95

2024-06-12 03:07 UTC, NJ97S commented on apis/axios.ts
>  instance.interceptors.response.use();
같이 구현하겠습니다...! 🥹🥹🥹

2024-06-12 08:38 UTC, wo-o29 approved these changes

2024-06-12 08:38 UTC, wo-o29 commented on pages/api/cookies.page.ts
> +  );
```suggestion
// 코드 제거
```
여기 코드는 없어도 될 것 같아요!

2024-06-12 08:38 UTC, wo-o29 commented on pages/sign-in/kakao/index.page.tsx
> +      notFound: true, // 404 페이지로 이동
```suggestion

```
여기서 에러 생기면 로그인 페이지로 가도 좋을 것 같아요!

2024-06-12 08:38 UTC, wo-o29 commented on pages/sign-in/kakao/index.page.tsx
> +}
```suggestion
interface ResponseType {
  id: number;
  isComplete: boolean;
  accessToken: string;
  refreshToken: string;
  // 액세스 토큰 만료, 리프레쉬 토큰 만료 추가하면 좋을 것 같습니다!
}
```

2024-06-12 10:35 UTC, merged