[feat] 추가정보 입력 시 이미지 추가 / access token 재발급
tickita-project/tickita-front pull request #42
Opened 2024-06-13 10:27 UTC by NJ97S

# 🎯 이슈 번호

- #39 #31 

## 🏁 작업 내용(필수)

- 추가 정보 입력 페이지에서 이미지도 넘길 수 있도록 코드를 추가하였습니다. (파일 용량 제한은 1MB 입니다.)
- 인가 정보가 필요한 api 요청 시, refresh token 만료기간이 남아있으면 access token이 재발급됩니다. 만약, refresh token이 만료되어 존재하지 않을 경우, 로그인 페이지로 이동합니다.

2024-06-14 08:05 UTC, wo-o29 requested changes
고생하셨습니다👏🙃👏🙃👏🙃👏🙃👏🙃👏🙃
토큰 만료 부분은 테스트하기가 힘들어서 디테일하게 파악하지는 못했네요... 개발하면서 여쭤보거나 문제 있으면 말씀드리겠습니다!!

2024-06-14 08:05 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    }
P4: 프로필 이미지나 카메라 아이콘 클릭했을 때 `<input type="file"/>` 이 클릭되는 방식을 구현하신 것 같은데 `button` 태그로 하기 보다는 `label` 태그의 `htmlFor`속성으로 연결하는게 더 시맨틱할 것 같아요!
```jsx
<label htmlFor="profileImage">
    // 프로필 이미지, 카메라 아이콘 등...
</label>
<input id="profileImage" type="file"/>
```

2024-06-14 08:05 UTC, wo-o29 commented on utils/getCookieValue.ts
이제 쿠키 마스터가 되셨군요....

2024-06-14 08:41 UTC, jae6269 approved these changes
수고하셨습니다 :) !

2024-06-14 08:41 UTC, jae6269 commented on apis/axios.ts
>      if (getIsServer()) {
p3: 
```suggestion
    if (getIsServer()&&context) {
```
로 수정해주시고 아래 옵셔널 지워주시면 더 좋을거같아요

2024-06-14 08:41 UTC, jae6269 commented on apis/axios.ts
> +        if (getIsServer()) {
여기도 &&context  로 해주세요!

2024-06-14 08:41 UTC, jae6269 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
p5: ㅋㅋㅋㅋ꽁꽁숨겨놓으셨네요 ! 위로해도상관없지않나요??

2024-06-14 08:41 UTC, jae6269 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +  const handleProfileImageButtonClick = () => {
p4: 바로할수도 있을거같아요
```suggestion
  const handleProfileImageButtonClick = () => profileImageInput.current?.click();
```

2024-06-14 08:41 UTC, jae6269 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    const imageFile = e.target.files[0];
p5: 정말 사소하지만 이런부분도 const 두줄을 이어붙이고 if를 띄워주시면 가독성 향상될거같스빈다

2024-06-14 10:32 UTC, NJ97S commented on apis/axios.ts
> +          REFRESH_TOKEN = getCookieValue(refreshTokenString, "REFRESH_TOKEN");
이거는 refreshToken의 값이 들어가는게 아니라, 쿠키 이름인 `REFRESH_TOKEN`이 필요한거라서 이렇게 사용했습니다!

대신 type으로 잡아서, `ACCESS_TOKEN`과 `REFRESH_TOKEN` 두 개만 들어갈 수 있도록 제한해두겠습니다 🫡

2024-06-14 10:46 UTC, NJ97S commented on pages/api/setCookies.page.ts
> +};
코드 한 번 짜고나서 자체적으로 리팩토링 하는 과정에서 early return을 적용해보고자 했었는데, 아래쪽은 신경을 많이 못썼던 것 같습니다😢

말씀해주신 것처럼, 아래에도 early return을 사용하는게 일관성이 있을 것 같아, 수정하도록 하겠습니다🫡🫡🫡

2024-06-14 10:49 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +  const [imgUrl, setImgUrl] = useState("");
이름이 너무 통일성이 없었군요🥹🥹🥹 수정하도록 하겠습니다!

2024-06-14 10:53 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +  const handleProfileImageButtonClick = () => {
개인적으로는 `if`문에서도 줄이지 않고 `{}`를 붙여주는 것처럼, 함수에서도 일관된 형태를 가져가고자 붙여주었습니다!!

지금보니 이 부분도 방식을 통일해야 할 것 같네요!! 세세한 부분까지 꼼꼼하게 봐주셔서 감사합니다🥹🥹🥹

2024-06-14 11:06 UTC, wo-o29 commented on apis/axios.ts
> +          REFRESH_TOKEN = getCookieValue(refreshTokenString, "REFRESH_TOKEN");
아 제 말은 `"ACCESS_TOKEN", "REFRESH_TOKEN"` 이라는 문자열이 여기 말고도 쿠키 넣을 때도 사용하고 중복되는 것 같아서 그 문자열을 상수화한 것을 사용하는 걸 말씀드린거였습니다!

2024-06-14 11:19 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +  const profileImageInput = useRef<HTMLInputElement>(null);
수정하겠습니다🫡🫡🫡

2024-06-14 11:21 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    const imageFile = e.target.files[0];
헉 이런 리뷰 너무 좋습니다🥹🥹🥹

2024-06-14 11:29 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    fileReader.readAsDataURL(imageFile);
이미지 미리보기 코드의 경우, S3 url을 받는 것이 아닌, 유저가 선택한 파일을 그대로 보여주는 것이기 때문에, 아래 서버 요청하는 코드에서 에러가 생기더라도 미리보기는 그대로 반영됩니다. 일반적인 경우에는, 서버에 요청을 보내고 다시 url을 받기까지의 기간이 길지 않겠지만, 딜레이 될 경우를 고려하였을 때, 이와 관계없이 바로 미리보기를 할 수 있게 해주는 것이 유저 경험에 좋다고 생각하여 이렇게 코드 작성을 하게 되었습니다.

다만, 말씀해주신 것처럼, S3 url 응답을 받지 못하는 상황에 대한 로직을 제가 추가하지 않...았네요...😢

이 부분은 우선은 응답을 받지 못했을 경우, `alert`를 띄워주는 코드를 추가해두고, 추후 토스트로 변경해보도록 하겠습니다! 또한, 응답을 받지 못했을 경우에는, 알림과 함께 미리보기 이미지도 삭제해주는 방향으로 해보겠습니다!

2024-06-14 11:35 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    fileReader.readAsDataURL(imageFile);
넵 알겠습니다!
저희는 `react-query`사용하니깐 `Optimistic Update(낙관적 업데이트)` 같은 것도 응용해보면 좋을 것 같아요
https://github.com/ssi02014/react-query-tutorial?tab=readme-ov-file#optimistic-update

2024-06-14 11:38 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    fileReader.readAsDataURL(imageFile);
역시 react-query 고수....👍👍👍

2024-06-14 11:47 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +          src={uploadedImage || "/icons/default-profile-image.svg"}
역시 카카오 개발자 이우혁 그는 신이야 😆😆😆

2024-06-14 11:49 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 실제로 화면에 보이는 요소가 아니기도 하고, `form` 전송 시 같이 전송되면 안되는 input이기 때문에 외부로 빼다보니 의도치않게 꽁꽁 숨겨버렸네요😆

2024-06-14 11:56 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
근데 훅폼의 `register`를 연결하지 않았으니깐 `form`안에 있어도 괜찮지 않나요??

2024-06-14 12:02 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
`form` 안에 넣으려면 넣을 수 있지만, 화면 상에 보이지 않고, 해당 input에 입력되는 데이터는 `submit` 시 실제로 넘어가는 데이터가 아니기 때문에, 따로 분리시키는게 더 좋을 것 같다는 생각이 들어서, 이렇게 코드를 작성하게 되었습니다 :)

2024-06-14 12:22 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
그렇게 생각할 수 도 있겠군요! 저는 오히려 같은 목적인 코드가 분리 되어 있어서 응집도가 떨어져서 코드를 파악하기 어려울 것 같다고 생각이 들었던 것 같아요.
사실 정답은 없는 것 같은데 저는 이 영상 보고 최대한 같은 목적인 코드는 응집 시키려고 하고 있는 것 같아요 코드 짜면서 많이 나오는 안티 패턴을 다루는 영상이여서 시간 나실 때 한번 보는 것도 추천드립니다!
https://www.youtube.com/watch?v=edWbHp_k_9Y

2024-06-14 12:30 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
저도 이 `<input>` 위치에 대해 고민을 정말 많이 해봤었는데, 우혁님 이야기 듣고 다시 생각해보니, 이렇게 `<button>` 태그 아래 쪽에다가 바로 넣어주는게 오히려 더 좋은 코드인 것 같다는 생각이 드네요😶 이렇게 해보는 건 어떻게 생각하실까용

```tsx
      <button
        type="button"
        onClick={handleProfileImageButtonClick}
        className={cn("profile-image-button")}
      >
        <Image
          src={uploadedImgUrl ?? "/icons/default-profile-image.svg"}
          alt="프로필 이미지"
          fill
          className={cn("profile-image")}
        />
        <Image
          src="/icons/camera-icon.svg"
          alt="카메라 아이콘"
          width={44}
          height={44}
          className={cn("camera-icon")}
        />
      </button>

      <input
        type="file"
        accept="image/*"
        ref={profileImageInputRef}
        onChange={handleProfileImageChange}
        className={cn("hidden-image-input")}
      />
```

2024-06-14 12:49 UTC, jae6269 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
저도이게좋을거같아요 밑으로놓으면 찾기어려워서

2024-06-14 12:51 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
버튼 누르면 input file 열리는게 목적인 것 같은데 `label`의 `htmlFor` 속성을 사용하면 똑같은 동작에 웹 접근성까지 챙길 수 있는 것 같아서 `button`을 `label`로 바꾸는게 더 시맨틱할 것 같다고 생각하긴해요!
그걸 떠나서 같은 목적의 코드를 뭉쳐두는건 좋을 것 같아요!!

2024-06-14 12:52 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +      <input
넵넵 우혁님께서 코드 리뷰 달아주신 부분도 확인 했습니다!! 다만, 지금 서버가 안열려있어서 제가 해당 페이지 접근이 안되는 상황이라ㅠㅠ 서버 돌아오면 수정해보겠습니다...! 🥹🥹🥹

2024-06-14 14:10 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +          src={uploadedImage || "/icons/default-profile-image.svg"}
제가 이미지 기본값을 `''`으로 잡아놔서 `??` 연산자를 사용했더니 사진이 나오지 않는군욬ㅋㅋㅋ `||`로 다시 수정해두겠습니다 😢

2024-06-14 14:50 UTC, wo-o29 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +          src={uploadedImage || "/icons/default-profile-image.svg"}
그러면 기본 값을 `null`로 바꾸는게 오히려 의도한 빈 값이라서 더 좋지 않나요??

2024-06-14 15:15 UTC, NJ97S commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +          src={uploadedImage || "/icons/default-profile-image.svg"}
어라... 그러네요...? 수정하겠습니다 🫡🫡🫡

2024-06-14 15:28 UTC, wo-o29 approved these changes

2024-06-14 15:53 UTC, wo-o29 approved these changes

2024-06-14 15:53 UTC, wo-o29 commented on middleware.page.ts
p4: 지금 상황에서는 문제가 없을 것 같은데 추후에 유지보수를 생각하고 요구사항이 늘어남에 따라`matcher`가 바뀌게 되면 내부 로직도 바껴야 하는 것 상황이 생길 것 같아요!
저도 미들웨어 설정은 안해봤는데 이전 팀원분은 `matcher`는 모든 페이지에 적용되게 하고 로그인 상태랑 현재 어느 페이지에 있는지에 따라 리다이렉트 시켜주신 것 같아요
- 이전 팀원분 코드
```js
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { AUTH_TOKEN_COOKIE_NAME } from './constants/auth';
import { getMeForServer, isDashboardAccessible } from './utils/auth';
import { PAGE_PATH } from './constants/pageUrl';

// 로그인하지 않은 유저만 접근할 수 있는 URL 정규식
const guestOnlyUrlRegex = /^(\/$|\/signup|\/login)/;
// 로그인한 유저만 접근할 수 있는 URL 정규식
const userOnlyUrlRegex = /^(\/mypage|\/dashboard|\/mydashboard)/;

export async function middleware(request: NextRequest) {
  const pathName = request.nextUrl.pathname;
  const accessToken = request.cookies.get(AUTH_TOKEN_COOKIE_NAME)?.value;
  const user = await getMeForServer(accessToken);
  const isLogin = user?.email ? true : false;

  // 로그인한 유저가 로그인하지 않은 유저만 접근할 수 있는 페이지에 접근했을 때 '내 대시보드' 페이지로 redirect 시킵니다.
  if (isLogin && guestOnlyUrlRegex.test(pathName)) {
    return NextResponse.redirect(new URL(PAGE_PATH.MY_DASHBOARD, request.url));
  }

  // 로그인하지 않은 유저가 로그인한 유저만 접근할 수 있는 페이지에 접근했을 때 '로그인' 페이지로 redirect 시킵니다.
  if (!isLogin && userOnlyUrlRegex.test(pathName)) {
    return NextResponse.redirect(new URL(PAGE_PATH.LOGIN, request.url));
  }

  if (pathName.startsWith(PAGE_PATH.DASHBOARD)) {
    const dashboardId = pathName.split('/')[2];
    const isAccessible = await isDashboardAccessible(accessToken, dashboardId);

    if (!isAccessible) {
      return NextResponse.redirect(
        new URL(PAGE_PATH.MY_DASHBOARD, request.url),
      );
    }
  }
}

// matcher에 포함된 URL 주소만 middleware가 동작합니다.
// 아래는 API routes를 포함해서 정적인 파일들을 제외한 모든 경로에 대해서 middleware를 동작하는 정규식입니다.
export const config = {
  matcher: ['/((?!api|images|svgs|_next/static|_next/image|favicon.ico).*)'],
};
```

2024-06-14 16:25 UTC, merged

2024-06-15 05:54 UTC, tead7 reviewed
수고하셨습니다

2024-06-15 05:54 UTC, tead7 commented on pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
> +    const { imgUrl } = res;
const { imgUrl }  = await postProfileImageUrl(formData); 
res가 그냥 전달의 역활이면 그냥 이렇게 바로 넣어주셔도 될 거 같네요