Feature/group page
tickita-project/tickita-front pull request #50
Opened 2024-06-15 16:30 UTC by wo-o29

# 🎯 이슈 번호

-  #26 

## 🏁 작업 내용(필수)

- 그룹 상세 페이지 작업

## 📢 참고 사항
추후 작업 예정
- 그룹 삭제 or 나가기 (api 아직 없음)
- 그룹 초대 (api 수정 예정)
- 그룹 초대 리스트 가져오기, 그룹 초대 취소 (api 아직 없음)
- 그룹 정보 변경 (api 아직 없음)
- 리더 위임, 멤버 추방하기 (api 아직 없음)
- 페이지 로딩 처리 (디자인 만드시는 중인 것 같아요)

빨간색 표시한 곳 공통 컴포넌트로 만들었습니다. 사다리꼴을 처음 해봐서 찾아서 만들긴 했는데 미흡하긴 하네요...
수정하실 부분있으면 수정하셔도 됩니다!
```jsx
<TitleBox tile="그룹 정보"/>
```
<img width="1665" alt="스크린샷 2024-06-16 오전 12 46 07" src="https://github.com/tickita-project/tickita-front/assets/154664697/80e10f91-c707-483a-bae1-9e79a3df18cc">

2024-06-15 17:11 UTC, NJ97S commented on components/ErrorFallBack/index.tsx
> +import { FallbackProps } from "react-error-boundary";
고수다... 👍👍👍

2024-06-15 17:11 UTC, NJ97S commented on components/Header/index.tsx
> +  const isCalendardPage = pathname === PAGE_PATH.CALENDAR;
P2: `isCalendarPage`로 변경되어야 할 것 같아요

2024-06-15 17:14 UTC, NJ97S commented on components/ProfileImage/index.tsx
> +  imageUrl: string | null | undefined;
P4: 이렇게도 바꿔볼 수 있을 것 같아요

```ts
imageUrl?: string | null;
```

2024-06-15 17:14 UTC, NJ97S commented on components/TitleBox/TitleBox.module.scss
> +  width: 103px; /* 내부 사다리꼴 width + border-left + border-right */
오우 디테일 하네요 👍👍👍

2024-06-15 17:14 UTC, NJ97S commented on components/TitleBox/TitleBox.module.scss
> +    width: 98px;
P2: `rem`으로 바꿔주시면 좋을 것 같아요

2024-06-15 17:16 UTC, NJ97S commented on hooks/useInviteGroupMember.ts
> +  });
react query 고수시네요 진짜 👍👍👍

2024-06-15 17:17 UTC, NJ97S commented on pages/dashboard/components/GroupList/index.tsx
> +  const selectId = Number(query.id);
P5: 이렇게 사이를 한 줄 띄워주셔도 좋을 것 같아요

```tsx
const { query } = useRouter();
const { data: groupList } = useGetGroupList();
const { openModal } = useModalStore();

const selectId = Number(query.id);
```

2024-06-15 17:21 UTC, NJ97S commented on pages/group/[id]/components/MemberList/MemberInfo/index.tsx
> +  const isMe = currentUserId === accountId; // 나인지 확인
P5: 여기도 중간에 한 줄 띄워주시면 가독성이 더 좋을 것 같아요 😶

```tsx
const { role, accountId, nickName, email, imageUrl } = MemberInfoData;

const [isMenuOpen, setIsMenuOpen] = useState(false);
const menuButtonRef = useRef<HTMLButtonElement>(null);

const isLeader = role === "OWNER"; // 리더인지 확인
const isMe = currentUserId === accountId; // 나인지 확인
```

or

```tsx
const [isMenuOpen, setIsMenuOpen] = useState(false);
const menuButtonRef = useRef<HTMLButtonElement>(null);

const { role, accountId, nickName, email, imageUrl } = MemberInfoData;

const isLeader = role === "OWNER"; // 리더인지 확인
const isMe = currentUserId === accountId; // 나인지 확인
```

2024-06-15 17:55 UTC, NJ97S requested changes
수고하셨습니다 🥰😆😍🥰😆😍🥰😆😍🥰😆😍

2024-06-16 09:28 UTC, wo-o29 commented on components/ProfileImage/index.tsx
> +  imageUrl: string | null | undefined;
타입에러 생기는거 임시로 막아둔거라서 추후에 로딩 처리 생기면 `undefined ` 제거 될 것 같습니다!

2024-06-17 04:49 UTC, NJ97S approved these changes

2024-06-17 07:38 UTC, jae6269 approved these changes
수고하셨습니다 !!

2024-06-17 07:38 UTC, jae6269 commented on pages/group/[id]/components/MemberList/MemberInfo/index.tsx
> +  const isLeader = role === "OWNER"; // 리더인지 확인
p3: isCurrentUserLeader 와는 다른 변수인가요??

2024-06-17 07:45 UTC, wo-o29 commented on components/Header/index.tsx
>      isAnimation.dashboard = true;
```js
const isAnimation = {
  dashboard: false,
  calendar: false,
};
```
`isAnimation`은 객체이기 때문에 내부 프로퍼티를 수정할 수 있습니다!

2024-06-17 07:47 UTC, wo-o29 commented on pages/group/[id]/index.page.tsx
> +  const { data: userInfo } = useGetUserInfo();
`Suggested`가 잘못 연결되있어서 `isCurrentUserLeader` 이 부분을 말씀해주신 것 같은데 제가 정의한 변수는 
- `isLeader`: 그룹에서 리더인지 파악(리더 뱃지를 표시)
- `isCurrentUserLeader`: 로그인 한 유저가 그룹에서 리더인지 파악(리더 위임, 멤버 추방 가능)

이렇게 2가지로 나눠서 사용중입니다!

2024-06-17 07:48 UTC, wo-o29 commented on pages/group/[id]/components/InviteForm/index.tsx
> +          <Input
일정쪽 api를 최우선으로 하고 그 이후에 만들 것 같습니다!

2024-06-17 07:49 UTC, wo-o29 commented on pages/group/[id]/components/MemberList/MemberInfo/index.tsx
> +  const isLeader = role === "OWNER"; // 리더인지 확인
https://github.com/tickita-project/tickita-front/pull/50#discussion_r1642345581
여기쪽 답변 참고해 주시면 될 것 같습니다!

2024-06-17 09:08 UTC, jae6269 commented on pages/group/[id]/components/InviteForm/index.tsx
> +          <Input
오 시간플랜까지 ! 너무 좋은거같아요

2024-06-17 09:09 UTC, jae6269 commented on pages/group/[id]/index.page.tsx
> +  const { data: userInfo } = useGetUserInfo();
확인했습니다 감사합니다 :)

2024-06-17 14:37 UTC, tead7 approved these changes

2024-06-17 16:45 UTC, merged