[feat] 조율 생성 완료 모달
tickita-project/tickita-front pull request #61
Opened 2024-06-18 12:51 UTC by tead7

# 🎯 이슈 번호

- #60 

## 🏁 작업 내용(필수)

-조율 성공 시 보여주는 모달을 작업했습니다.

## 📢 참고 사항

- 모달 연결은 아직 안 했습니다.(추후에 연결 예정)
- gif 를 아직 안 넣었습니다.(새벽 님에게 요청해서 받을 예정 / 로띠로 받을 수도 있습니다.)

2024-06-18 13:09 UTC, wo-o29 approved these changes
고생하셨습니다👍☁️🫡👍☁️🫡👍☁️🫡👍☁️🫡

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +        font-size: 1.063rem;
```suggestion
        font-size: 1.063rem;
```
디테일 하시군요👍👍👍

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +        color: gray;
```suggestion
        color: gray;
```
p4: 여기도 색상 변수가 사용되고 있지 않는 것 같아요!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +        color: red;
```suggestion
        color: red;
```
p4: 여기도 색상 변수가 사용되고 있지 않는 것 같아요!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +      color: white;
```suggestion
      background: #3360ff;

      color: white;
```
p4: 여기도 색상 변수가 사용되고 있지 않는 것 같아요!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +      font-size: 1rem;
```suggestion
```
p4: 기본 값이라서 안적어주셔도 될 것 같습니다!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +        text-align: left;
```suggestion
        text-align: left;
```
`text-align: left` 필요한 css이신가요?!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/index.tsx
> +        >
```suggestion
        <button
          type="button"
          className={cn("modal-button")}
          onClick={() => router.push(PAGE_PATH.MY_PAGE) }>
```
p4: 버튼 타입을 명시하고 `onClick`에서 중괄호 생략해도 좋을 것 같아요!

2024-06-18 13:09 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/index.tsx
> +                하나의 일정이 <b>과반수 이상</b> 받은 경우
```suggestion
                하나의 일정이 <b>과반수 이상</b> 받은 경우
```
p4: `<b>` 태그 좋네요👏👏👏
하지만 다른 태그쪽에서 `div`태그가 조금 많은 것 같아요 `p`, `span` 태그도 적절히 사용해주는 것도 좋을 것 같아요!

2024-06-19 08:09 UTC, NJ97S commented on components/Modal/CoordinationSuccess/index.tsx
> +      </div>
P4:`onClick` 이벤트로 페이지 이동만 시키는 거면, `<button>` 태그가 아니라 `<Link>` 컴포넌트를 사용해도 될 것 같아요

2024-06-19 08:10 UTC, NJ97S reviewed
수고하셨습니다 🔥😍🔥😍🔥😍🔥😍🔥😍🔥😍

2024-06-19 08:10 UTC, NJ97S approved these changes

2024-06-19 08:18 UTC, jae6269 requested changes
수고하셨습니다 :) 전체적으로 태그를 다양하게 사용하면 좋을거같아요!

그리고 저희는 css module를 사용하고 있기때문에,
그 장점을 살려주시면 좋을거같아요

ex)  modal-title , modal-title-main 이런식으로 bem 방식에서 하는것처럼 쪼개지말고
title, main, subtitle 이런식으로 하는게 module.css의 장점을 살리는것이란 생각이 듭니다!

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +      <div className={cn("modal-footer")}>
p3: 버튼도 블럭요소이고 내부에 버튼하나면 div를 없애도 괜찮을거같아요!

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +          <div className={cn("modal-body-sub-text")}>
p4: 저는 html 작성할떄에 
div는 이런 경우에 사용합니다
1. 내부에 요소가 여러개 있을때
2. "구역"을 나눌때
이렇게 텍스트가 들어가는 경우엔 가능하면 p, span 같은 태그를 사용해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +          <div className={cn("modal-body-sub-text")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +              <div className={cn("modal-body-content-text-sub")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +              <div className={cn("modal-body-content-text")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +              <div className={cn("modal-body-content-text-sub")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +              <div className={cn("modal-body-content-text")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +          <div className={cn("modal-title-main")}>투표 요청이 완료되었어요</div>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:18 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +          <div className={cn("modal-title-sub")}>
p4: p태그로 해주시면 좋을거같아요

2024-06-19 08:21 UTC, jae6269 commented on components/Modal/CoordinationSuccess/index.tsx
> +      </div>
저도 같은 생각입니다! 동작이 일어나지 않는다면 Link가 맞을거같아요

2024-06-19 11:04 UTC, wo-o29 commented on components/Modal/CoordinationSuccess/index.tsx
> +      </div>
저도 이것만 보면 같은 생각이지만 아마 지금 진호님 로직이 다 완성이 안된 것 같아서 추후를 생각해보면 확인 버튼을 클릭했을 때 
페이지 이동뿐만 아니라 모달을 닫는 `closeModal()` 함수도 추가되서 버튼을 사용하는 것도 좋을 것 같네요🙃

2024-06-19 11:12 UTC, tead7 commented on components/Modal/CoordinationSuccess/CoordinationSuccess.module.scss
> +        font-weight: 400;
수정완료~

2024-06-30 13:58 UTC, closed without merging