[feat] 알림 팝업 구현
tickita-project/tickita-front pull request #66
Opened 2024-06-20 18:26 UTC by NJ97S

# 🎯 이슈 번호

- #65 

## 🏁 작업 내용(필수)

- 알림 팝업을 구현하였습니다.
- 알림 관련된 모든 컴포넌트에 api를 연동하였습니다.

## 💬 리뷰 요구 사항

- @wo-o29 혹시 우혁님 작업 내용과 겹치면 말씀해주시면 감사하겠습니다.

2024-06-20 18:54 UTC, wo-o29 requested changes

2024-06-20 18:54 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +          {allNotifications?.count ? (
```suggestion
          {allNotifications?.count ? (
```
P3: `count`는 읽지 않은 알림의 개수여서 렌더링과는 무관할 것 같아요!
예를 들어서 알림을 다 읽어서 `count`가 0인 경우에는 알림이 없다고 나오는 이슈가 있을 것 같네요

2024-06-20 18:54 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +        <figcaption className={cn("notification-count")}>{allNotifications?.count}</figcaption>
```suggestion
       { allNotifications?.count > 0 && <figcaption className={cn("notification-count")}>{allNotifications?.count}</figcaption> }
```
P4: `count`가 0인 경우에는 빨간색 숫자를 나타내는 태그가 렌더링되지 않아야 할 것 같아요!

2024-06-20 18:54 UTC, wo-o29 commented on pages/dashboard/components/NotificationCenter/index.tsx
> +        {allNotifications?.count ? (
```suggestion
        {crewNotificationResponse.length > 0 ? (
```
P4: 여기도 `count`로 구분하지 않고 `crewNotificationResponse.length`로 판단해야 할 것 같네요!

2024-06-20 18:54 UTC, wo-o29 commented on hooks/useGetNotifications.ts
> +  });
P3: 쿼리 키 상수화와 `refetchInterval` 설정이 필요할 것 같아요!

2024-06-21 05:10 UTC, NJ97S commented on utils/changeLocalTime.ts
이 부분 우혁님이 만들어주신 유틸 함수로 합치겠습니다!

2024-06-21 05:31 UTC, wo-o29 approved these changes
수고하셨습니다👍☁️🍃👍☁️🍃👍☁️🍃👍☁️🍃👍☁️🍃

2024-06-21 05:31 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +  const [isClicked, setIsClicked] = useState(false);
```suggestion
  const [isPopupView, setIsPopupView] = useState(false);
```
P5: `isPopupView`와 같이 조금 더 명확하게 네이밍을 지어도 좋을 것 같아요~!

2024-06-21 05:31 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +    if (!notificationInfo) return;
```suggestion
    if (!notificationInfo){
     return;
    }
```
P4: 저희 컨벤션에 맞게 1줄이여도 중괄호로 사용하는게 좋을 것 같아요!

2024-06-21 05:31 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +          {notificationInfo?.crewNotificationResponse.length ? (
```suggestion
          {notificationList.length > 0 (
```
P4: 이 부분은 이름이 너무 길어서 위에서 `notificationInfo`을 한번 분해해서 사용하면 가독성 향상에 도움이 될 것 같아요!
```js
const { count, crewNotificationResponse: notificationList } = notificationInfo
```
그리고 추가적으로 저는 `notificationList.length > 0` 이렇게 사용하는게 좀 더 명시적이고 완전한 조건식을 제공해서 이 방식을 선호합니다!

2024-06-21 05:31 UTC, wo-o29 commented on components/NotificationPopup/index.tsx
> +    return notificationInfo.count < 10 ? notificationInfo.count : "+";
```suggestion
    return count < 10 ? count : "9+";
```
P4: 이렇게 하면 카운트가 10이 넘으면 `+`만 나오지 않나요??

2024-06-21 05:44 UTC, NJ97S commented on components/NotificationPopup/index.tsx
> +    return notificationInfo.count < 10 ? notificationInfo.count : "+";
헉... 새벽에 코드 짰더니... 정신줄을 놓고 만들었나봐여... 수정하겠습니다ㅠㅠ

2024-06-21 07:25 UTC, jae6269 approved these changes
수고하셨습니다 :)

2024-06-21 07:25 UTC, jae6269 commented on components/Notification/BaseNotification/index.tsx
이파일에서 closeRef 걸려있긴한데 어디사용되는건가요?

2024-06-21 07:25 UTC, jae6269 commented on components/NotificationPopup/index.tsx
> +    setIsPopupView(!isPopupView);
```suggestion
    setIsPopupView((prev)=>!prev);
```
로 해주시면 좋을거같아요!

2024-06-21 07:25 UTC, jae6269 commented on components/NotificationPopup/index.tsx
> +  const handleBellClick = () => {
onoff 만의 기능을 가진다면 handleBellToggle 도 네이밍 괜찮을거같아요

2024-06-21 07:25 UTC, jae6269 commented on hooks/useGetProfileImage.ts
> +const useGetProfileImage = (initialImgUrl: string | null) => {
hook return type 지정해주세요!

2024-06-21 07:25 UTC, jae6269 commented on pages/my-page/components/ProfileEditForm/index.tsx
> +  const { uploadedImgUrl, imgUrl, handleProfileImageChange } = useGetProfileImage(userInfo.image);
hook return type이 없어서 any로 잡히고있는거같아요!

2024-06-21 07:25 UTC, jae6269 commented on utils/formatKoreanDateTime.ts
> +export const formatKoreanDateTime = (date: string) => {
이거 date 타입 정확하게 하는게 좋을거같아서 chat gpt한테 물어보니까
type DateString = 
  | `${number}-${number}-${number}` // YYYY-MM-DD
  | `${number}-${number}-${number}T${number}:${number}:${number}Z` // YYYY-MM-DDTHH:mm:ssZ
  | `${number}-${number}-${number}T${number}:${number}:${number}.${number}Z` // YYYY-MM-DDTHH:mm:ss.SSSZ
  | `${number}-${number}-${number} ${number}:${number}` // YYYY-MM-DD HH:mm
  | `${number}-${number}-${number} ${number}:${number}:${number}` // YYYY-MM-DD HH:mm:ss
  
  이런식으로 알려줘서 이거써도될거같아요

2024-06-21 08:39 UTC, NJ97S commented on pages/my-page/components/ProfileEditForm/index.tsx
> +  const { uploadedImgUrl, imgUrl, handleProfileImageChange } = useGetProfileImage(userInfo.image);
혹시 어디가 `any`로 잡히고 있다고 말씀해주신 건지 알려주실 수 있을까용👀

2024-06-22 01:44 UTC, merged