[feat]일정생성모달구현
tickita-project/tickita-front pull request #79
Opened 2024-06-21 17:45 UTC by jae6269

# 🎯 이슈 번호

- #

## 🏁 작업 내용(필수)

- 일정생성모달 구현입니다.
- 

## 💬 리뷰 요구 사항

-
-

## 📢 참고 사항

- 지금 참가자 선택이 ["1" , "2"]이런식으로 요청이 가고있는데 도저히 해결이 안되어서 혹시 이부분 해결법 아신다면 알려주시면 감사하겠습니다 ㅠ 지금 참가자 선택안하고 보내면( 나 혼자인 일정) 은 요청 잘 가는데 이거만 고쳐서 다시 말씀드릴게요!
-

2024-06-22 04:06 UTC, wo-o29 requested changes
수고하셨습니다👏🙃☁️👏🙃☁️👏🙃☁️👏🙃☁️
코드가 전체적으로 조건부 렌더링이랑 삼항 연산자가 많아서 가독성이 떨어지는 것 같네요 시간이 바쁘셔서 어쩔 수 없겠지만, 추후에 리팩토링 의사기 있다고 하시면 컴포넌트를 분리해서 가독성을 높여봐도 좋을 것 같습니다!


<img width="623" alt="스크린샷 2024-06-22 오후 12 14 35" src="https://github.com/tickita-project/tickita-front/assets/154664697/7514f8bb-b162-464e-ab8c-0fb12827efbd">

<img width="650" alt="스크린샷 2024-06-22 오후 12 14 30" src="https://github.com/tickita-project/tickita-front/assets/154664697/e5bd3957-6a2b-48ed-939e-a388ef33048a">
여기서 그룹 선택하기 전이랑 그룹 선택한 후에 모달 높이가 달라져서 약간의 레이아웃 쉬프트가 생기는 것 같아서 그룹 선택하기 전에 미리 높이를 지정해도 좋을 것 같아요!

추가적으로 지금 빌드 에러가 생기시는 것 같아서 `Request changes` 남겨놓을게요

`지금 참가자 선택이 ["1" , "2"]이런식으로 요청이 가고있는데 도저히 해결이 안되어서 혹시 이부분 해결법 아신다면 알려주시면 감사하겠습니다 ㅠ 지금 참가자 선택안하고 보내면( 나 혼자인 일정) 은 요청 잘 가는데 이거만 고쳐서 다시 말씀드릴게요!`

이 말씀은 제가 잘 이해하지 못해서 디스코드 같은걸로 한번 더 설명주시면 도움이 될 수 있다면 도움 드리도록 하겠습니다~!

2024-06-22 04:06 UTC, wo-o29 commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +                        id={`member-${member.accountId}`}
```suggestion
                        id={member.accountId}
```
P4: `member.accountId`이렇게만 적었을 때 생기는 문제가 있을까요??

2024-06-22 04:35 UTC, jae6269 commented on hooks/useScheduleCreate.ts
아 우혁님이 create 먼저쓰셔서 네이밍 맞춘건데 기존껄 안지웠네요!

2024-06-22 05:01 UTC, jae6269 commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +                        id={`member-${member.accountId}`}
number 형식은 string혛식에 넣을 수 없다고 나와요!

2024-06-22 05:06 UTC, jae6269 commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +    reset();
처음엔 이거 안써주면 모달껏다 켯을때 그룹 선택이 그대로 남아있었는데 , 지금은 상태로 바꿔서 뺴줘도될거같네요!

2024-06-22 06:47 UTC, NJ97S commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +          {...register("title", { required: true })}
P3: 일정 이름을 입력하지 않고 focusout 했을 경우, 일정 이름을 입력해야 한다는 걸 확실하게 보여주면 좋을 것 같아요

2024-06-22 06:55 UTC, NJ97S commented on hooks/useScheduleCreate.ts
> +import { postSchedule } from "@/apis/apis";
P1: 해당 파일에 `postSchedule`이 없어요...!
```
Module '"@/apis/apis"' has no exported member 'postSchedule'.ts(2305)
```

2024-06-22 06:56 UTC, NJ97S commented on hooks/useScheduleCreate.ts
> +      queryClient.invalidateQueries({ queryKey: scheduleKey.lists() });
P1: 파라미터 하나가 필요한데, 현재는 파라미터가 없어서 ts 에러가 나고 있어요 👀
```
Expected 1 arguments, but got 0.ts(2554)
queryKey.ts(25, 11): An argument for 'crewId' was not provided.
```

2024-06-22 06:57 UTC, NJ97S requested changes
수고하셨습니다 🐰🔥😍🤓🐰🔥😍🤓🐰🔥😍🤓🐰🔥😍🤓

2024-06-22 17:15 UTC, jae6269 commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +          {...register("title", { required: true })}
제 생각에는필수입력값에 빨간색 별표같은걸 추가하는걸 생각하고있어요!

2024-06-22 17:19 UTC, jae6269 commented on components/Modal/Schedule/ScheduleCreate/index.tsx
> +    fetchGroupInfo();
좋은의견 감사합니다!

2024-06-22 17:35 UTC, jae6269 commented on constants/queryKey.ts
> +  details: (crewId: number) => [...scheduleKey.all, "detail", crewId] as const,
여기선 아마 details는 안쓸거같아서 삭제해야할거같네요..!

2024-06-22 17:38 UTC, jae6269 commented on constants/queryKey.ts
> +  details: (crewId: number) => [...scheduleKey.all, "detail", crewId] as const,
아 details를 사실 밑에 detail(일정상세보기)을 위해서 만들었는데 그걸 lists에서 하면되겠네요
그런데 여기서 lists 로 일정들 목록을 크루 id 별로 가져오는데 사실저희가 "상세" 데이터랑 차이가 없어서
detail이 필요한가 싶거든요 어떻게보시나요?

2024-06-22 17:42 UTC, NJ97S approved these changes

2024-06-23 05:44 UTC, wo-o29 approved these changes

2024-06-23 05:44 UTC, wo-o29 commented on constants/queryKey.ts
> +  details: (crewId: number) => [...scheduleKey.all, "detail", crewId] as const,
물론 제 방식이 정답은 아니겠지만 저였다면 이렇게 했을 것 같아요!
```ts
interface ScheduleFilterType {
  crewId: number;
  startDate: string;
  endDate: string;
}

export const scheduleKey = {
  all: ["schedule"] as const, // 전체 관리
  lists: () => [...scheduleKey.all, "list"] as const, // 일정 리스트(전체)
  list: (filter: ScheduleFilterType) => [...scheduleKey.lists(), { filter }] as const, // 일정 리스트(특정 조건)
  details: () => [...scheduleKey.all, "detail"] as const, // 일정 상세 -> 기본 키 제공, 유지보수 용이
  detail: (scheduleId: number) => [...scheduleKey.details(), scheduleId] as const, // 일정 상세(특정 일정)
};
```

2024-06-23 07:50 UTC, jae6269 commented on constants/queryKey.ts
> +  details: (crewId: number) => [...scheduleKey.all, "detail", crewId] as const,
아 저는이 detail 부분을 다 없애버릴까 생각했는데 생각해보니까 
대시보드에서도 상세를 사용해야해서 써야할거같네요..!
일단 이런식으로 해보고 변경이 필요하면 해보겠습니다!

2024-06-23 07:50 UTC, merged